import {createContext,useContext,useEffect,useRef,useState} from 'react'
import type {ReactNode} from 'react'
import {CircleHelp,UserRound,Moon,Sun,Maximize,Minimize,X,Download} from 'lucide-react'
import {courseConfig} from './config'
type Profile={name:string;position:string;department:string}
const key='lab-template:'+import.meta.env.BASE_URL
const read=<T,>(k:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(key+k)||'null')??f}catch{return f}}
const Context=createContext({materials:'',profile:{name:'',position:'',department:''},openSettings:()=>{},registerDownloads:(_fn:(n:number|null)=>Promise<void>)=>{}})
export const usePreferences=()=>useContext(Context)
export function PreferencesProvider({children}:{children:ReactNode}){const [profile,setProfile]=useState<Profile>(()=>read(':profile',{name:'',position:'',department:''}));const [materials,setMaterials]=useState(()=>read(':materials',courseConfig.materialsUrl));const [open,setOpen]=useState(false);const download=useRef<(n:number|null)=>Promise<void>>(async()=>{});useEffect(()=>{document.documentElement.dataset.theme=read(':theme','light')},[]);return <Context.Provider value={{materials,profile,openSettings:()=>setOpen(true),registerDownloads:fn=>{download.current=fn}}}>{children}{open&&<Settings downloadSemester={n=>download.current(n)} profile={profile} materials={materials} close={()=>setOpen(false)} save={(p,m)=>{setProfile(p);setMaterials(m);localStorage.setItem(key+':profile',JSON.stringify(p));localStorage.setItem(key+':materials',JSON.stringify(m));setOpen(false)}}/>}</Context.Provider>}
export function SiteControls({downloadSemester}:{downloadSemester:(n:number|null)=>Promise<void>}){const p=usePreferences();const [theme,setTheme]=useState(()=>read(':theme','light'));const [full,setFull]=useState(false);useEffect(()=>{p.registerDownloads(downloadSemester)});const [error,setError]=useState('');useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem(key+':theme',JSON.stringify(theme))},[theme]);useEffect(()=>{const update=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update)},[]);return <><div className="course-controls"><span>{p.profile.name||'Лабораторный практикум'}{p.profile.position&&' · '+p.profile.position}{p.profile.department&&' · '+p.profile.department}</span><button className="button secondary" onClick={p.openSettings}><UserRound size={18}/>Настройка перед занятием</button><button className="icon-button" aria-label={theme==='light'?'Включить тёмную тему':'Включить светлую тему'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><a className="icon-button" href={`${import.meta.env.BASE_URL}guide.html`} target="_blank" rel="noopener noreferrer" title="Как пользоваться сайтом" aria-label="Как пользоваться сайтом"><CircleHelp size={18}/></a><button className="icon-button" aria-label="Полноэкранный режим" onClick={async()=>{try{if(full)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setError('Полноэкранный режим недоступен в этом окне браузера.')}}}>{full?<Minimize size={18}/>:<Maximize size={18}/>}</button></div>{error&&<p className="package-error" role="alert">{error}</p>}</>}
function Settings({profile,materials,save,close,downloadSemester}:{downloadSemester:(n:number|null)=>Promise<void>;profile:Profile;materials:string;save:(p:Profile,m:string)=>void;close:()=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [p,setP]=useState(profile);const [m,setM]=useState(materials);const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal()},[]);return <dialog className="settings-dialog" ref={dialog} onCancel={close}><div className="settings-heading"><h2>Настройка перед занятием</h2><button className="icon-button" aria-label="Закрыть настройки" onClick={close}><X/></button></div><form onSubmit={e=>{e.preventDefault();if(m&&!/^https?:\/\//i.test(m)){e.currentTarget.querySelector('input[type=url]')?.setAttribute('aria-invalid','true');return}save(p,m)}}>{(['name','position','department'] as const).map((k,i)=><label key={k}>{['ФИО преподавателя','Должность','Кафедра или лаборатория'][i]}<input value={p[k]} onChange={e=>setP({...p,[k]:e.target.value})}/></label>)}<label>Ссылка на материалы<input type="url" placeholder="https://…" value={m} onChange={e=>setM(e.target.value)}/></label><p>Данные сохраняются в этом браузере. Выберите архив для текущего варианта ниже.</p><section className="semester-downloads"><h3>Скачать лабораторные работы</h3><p>Архивы выбранного на главной странице варианта: задания, шаблоны и данные.</p>{[...courseConfig.semesters,null].map(sem=><button type="button" className="button secondary" key={sem||'all'} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await downloadSemester(sem)}catch{setError('Не удалось собрать архив. Повторите скачивание.')}finally{setBusy(false)}}}><Download size={17}/>{busy?'Подготовка…':sem?`${sem} семестр`:'Все семестры'}</button>)}{error&&<p role="alert">{error}</p>}</section><button className="button primary" type="submit">Сохранить</button></form></dialog>}
